name: indoscape
description: An application to explore Indonesia
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.5.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  intl: ^0.18.1
  skeletons: ^0.0.3
  http: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  flutter_dotenv: ^5.1.0
  introduction_screen: ^3.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/json/food.json
    - lib/assets/images/indonesiaMap.jpg
    - lib/assets/images/bgBromo.jpg
    - lib/assets/images/bromo.jpg
    - lib/assets/images/city.png
    - lib/assets/images/culture.png
    - lib/assets/images/food.png
    - lib/assets/images/info.png
    - lib/assets/images/mountain.png
    - lib/assets/images/museum.png
    - lib/assets/images/province.png
    - lib/assets/images/film.png
    - lib/assets/images/travel.png
    - lib/assets/images/bakso.jpg
    - lib/assets/images/sambalGorengTempe.jpg
    - lib/assets/images/rujakCingur.jpg
    - lib/assets/images/pindangIkan.jpg
    - lib/assets/images/lumpia.jpg
    - lib/assets/images/pecelLele.jpg
    - lib/assets/images/kerakTelor.jpg
    - lib/assets/images/nasiKunyit.jpg
    - lib/assets/images/pisangGoreng.jpg
    - lib/assets/images/sotoBetawi.jpg
    - lib/assets/images/ketoprak.jpg
    - lib/assets/images/nasiPadang.jpg
    - lib/assets/images/pempek.jpg
    - lib/assets/images/martabak.jpg
    - lib/assets/images/nasiUduk.jpg
    - lib/assets/images/sotoAyam.jpg
    - lib/assets/images/rujak.jpg
    - lib/assets/images/sateAyam.jpg
    - lib/assets/images/gadoGado.jpg
    - lib/assets/images/rendang.jpg
    - lib/assets/images/nasiGoreng.jpg